name = "hush"
description = "A gentle and responsive Zola theme for product sites."
license = "MIT"
homepage = "https://github.com/azriel91/hush"
min_version = "0.11.0"
demo = "https://peace.mk"

[extra]

[author]
name = "Huhu teams (Juice) and Azriel"
homepage = "https://peace.mk"
